# Generated by Django 4.1.1 on 2022-09-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Automovil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("matricula", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_date", models.DateField()),
                ("name", models.CharField(default="", max_length=50)),
                ("description", models.TextField()),
                ("technician", models.CharField(default="", max_length=50)),
                ("price", models.CharField(max_length=50)),
                (
                    "related_vehicle",
                    models.ForeignKey(
                        blank=True,
                        default="None",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auto.automovil",
                    ),
                ),
            ],
        ),
    ]
