# Generated by Django 4.1.1 on 2022-09-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='technician',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
