# Generated by Django 4.1.1 on 2022-09-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automovil",
            name="matricula",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
