on: push
name: deploy
jobs:
        deploy:
                name: deploy app
                runs-on: ubuntu-latest
                steps:
                        - name: build and push to dockerhub
                          uses: actions/checkout@master
                        - name: Run Super-Linter
                          uses: github/super-linter@v3
                          env:
                                DEFAULT_BRANCH: main
                                GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
                        - name: push to docker-hub
                          uses: docker/build-push-action@v2
                          with:
                                  username: ${{ secrets.DOCKER_USERNAME }}
                                  password: ${{ secrets.DOCKER_PASSWORD }}
                                  repository: ${{ github.repository }}
                                  tag_with_ref: true
                                  tag_with_sha: true
                                  tags: ${{ github.sha }}
