on: push
name: deploy
jobs:
        deploy:
                name: deploy app
                runs-on: ubuntu-latest
                strategy:
                        max-parallel: 4
                        matrix:
                                python-version: [ 3.7, 3.8, 3.9 ]
                steps:
                        - uses: actions/checkout@v3
                        - name: Set up Python ${{ matrix.python-version }}
                          uses: actions/setup-python@v3
                          with:
                                  python-version: ${{ matrix.python-version }}
                        - name: Install Dependencies
                          run: |
                                  python -m pip install --upgrade pip
                                  pip install -r requirements.txt
                        - name: Run Tests
                          run: |
                                  pytest
                        - name: push to docker-hub
                          uses: docker/build-push-action@v2
                          with:
                                  username: ${{ secrets.DOCKER_USERNAME }}
                                  password: ${{ secrets.DOCKER_PASSWORD }}
                                  repository: ${{ github.repository }}
                                  tag_with_ref: true
                                  tag_with_sha: true
                                  tags: ${{ github.sha }}
